---
- name: Setup pgmaster
  hosts: pgmaster
  become: yes
  become_method: sudo
  gather_facts: yes
  tags: [pgmaster]
  vars:
     replica_password: ‘replica123’
     pg_bin: '/opt/PostgreSQL-12.0/bin/psql -c '
  tasks:
  - name: Update /pgdatabase/data/postgresql.conf
    lineinfile:
       path: /pgdatabase/data/postgresql.conf
       regexp: “{{ item.From }}”
       line: “{{ item.To }}”
    with_items:
         - { From: “#listen_addresses = ‘localhost’”, To: 'listen_addresses = {{ ansible_default_ipv4.address }}’ }
         - { From: ‘#wal_level = replica’, To: ‘wal_level = replica’ }
         - { From: ‘#synchronous_commit = on’, To: ‘synchronous_commit = local’ }
         - { From: ‘#archive_mode = off’, To: ‘archive_mode = on’ }
         - { From: “#archive_command = ‘’”, To: “archive_command = ‘testing’” }
         - { From:  ‘#max_wal_senders = 0’, To: ‘max_wal_senders = 2’ }
